### ISSUE TITLE
feature req: track laps and calculate distance

### ISSUE THREAD

**Issue by nutpantz** [Baltasarq/nadamillas#4]
As a new swimmer i will be lucky to do 15 laps at the 25 meter pool. Which is only 750m.
It would be nice if i could track such info in this app. 
Maybe keep track of different pools or swimming areas with the distance each lap there is, then users could just input the number of laps and the app would do the math for the distance.

**Comment by Baltasarq** [comment]
That's an interesting new feature. I'll keep you posted!

**Comment by Baltasarq** [comment]
Done. You can wait for the new version to propagate from Google Play or install the last release from the APK. Thanks for your interest!!

**Comment by Baltasarq** [comment]
It's already online!!

**Comment by nutpantz** [comment]
I'm on fdroid, thanks for your work

**Comment by Baltasarq** [comment]
Have you installed the APK, then? I'm afraid the app is not in FDroid. I checked out what it was needed to get so, but it's too much work.

**Comment by networkjanitor** [comment]
> I'm afraid the app is not in FDroid.

FYI: while it is not in the main F-Droid repo, it is in the IzzyOnDroid repo, where your recent release(s) should appear automatically soon: https://apt.izzysoft.de/fdroid/index/apk/com.devbaltasarq.nadamillas

**Comment by nutpantz** [comment]
That is great.

**Comment by billie80** [comment]
Currently automated updates do not work for the IzzyOnDroid Repo because of #9. For now I requested a manual update to 1.2.7.

**Comment by IzzySoft** [comment]
Which was done right away. Would appreciate that minor fix to `versionName` to get the automated updates working :wink:
