### ISSUE TITLE
feature req: track different swimming strokes

### ISSUE THREAD

**Issue by nutpantz** [Baltasarq/nadamillas#8]
it might be interesting to track primary swimming strokes.

**Comment by Baltasarq** [comment]
Can you elaborate? Do you just mean a new field to store the number of strokes in the session?

**Comment by nutpantz** [comment]
If you are doing back stroke, freestyle or something else for the laps..  maybe set custom names as i understand names change with location or county

**Comment by Baltasarq** [comment]
Not sure. What about a notes field that you can fill with whatever details you like?

**Comment by nutpantz** [comment]
That would work, it would be nice to have a chart that said 80% freestyle etc.. but hardly required.
If it was user custom able,vi could even see it being used to record pull or push laps, laps with fins or any other training aid..

But like i said hardly required

**Comment by Baltasarq** [comment]
Feature added in the form of a notepad for comments.
