### ISSUE TITLE
Updates not automatically detected in IzzyOnDroid F-Droid Repo

### ISSUE THREAD

**Issue by billie80** [Baltasarq/nadamillas#9]
I recently installed your App from the IzzyOnDroid F-Droid [Repository](https://apt.izzysoft.de/fdroid/index/apk/com.devbaltasarq.nadamillas). I don't know who requested the inclusion there. Anyway your recent updates for 1.2.6 and 1.2.7 have not been detected there automatically.

I think the update check uses the latest Git tag (in this case v1.2.7), strips the prepending v and compares it with the latest versionName in the repository.

However for some reason the versionName for the previous version was 1.2.420230823. When comparing this versions using semantic versioning 1.2.420230823 > (v)1.2.7, thus the update is not detected automatically.

I think the reason is the definition of versionName and a date as versionNameSuffix in app/build.gradle. Im combination the final version name is then versionName + versionNameSuffix.

So would it be possible to add a dot between versionName and versionNameSuffix? The next update still needs to be triggered manually because 1.2.720231127 > (v)1.2.8 but for starting with the next it would work because e.g. 1.2.8.20231201 < (v)1.2.9.
Another solution would be removing versionNameSuffix entirely. Then after the manual update it would be 1.2.8 < (v)1.2.9
Or adding the suffix without dot to the tag to get 1.2.820231201 < (v)1.2.920231202. However this version scheme looks a bit strange to be honest.
Adding the suffix separated with a dot to tag and versionName should also work. Then we get 1.2.8.20231201 < (v)1.2.9.20231202

So there are many options (hope I did mix something up) and it would be great if you could implement one of them to allow automated updates.

Thanks for reading all this. 😃
Daniel

**Comment by Baltasarq** [comment]
> So would it be possible to add a dot between versionName and versionNameSuffix? The next update still needs to be triggered manually because 1.2.720231127 > (v)1.2.8 but for starting with the next it would work because e.g. 1.2.8.20231201 < (v)1.2.9.

I've added a dot ('.') as the prefix of the version suffix.
Thanks for the heads up.

**Comment by billie80** [comment]
Great! Thank you very much!
